2024-10-06 09:50:41.236 [info] (Client) Pylance async client (2024.9.2) started with python extension (2024.16.0)
2024-10-06 09:50:42.171 [info] [Info  - 9:50:42 AM] (3071) Server root directory: file:///home/ec2-user/.vscode-server/extensions/ms-python.vscode-pylance-2024.9.2/dist
2024-10-06 09:50:42.172 [info] [Info  - 9:50:42 AM] (3071) Pylance language server 2024.9.2 (pyright version 1.1.378, commit ce64adc1) starting
2024-10-06 09:50:42.181 [info] [Info  - 9:50:42 AM] (3071) Starting service instance "ec2-user"
2024-10-06 09:50:42.253 [info] [Info  - 9:50:42 AM] (3071) Setting environmentName for service "ec2-user": "3.8.16 (global)"
2024-10-06 09:50:42.253 [info] [Info  - 9:50:42 AM] (3071) Setting pythonPath for service "ec2-user": "/usr/bin/python3.8"
2024-10-06 09:50:42.254 [info] [Info  - 9:50:42 AM] (3071) No include entries specified; assuming /home/ec2-user
2024-10-06 09:50:42.255 [info] [Info  - 9:50:42 AM] (3071) Auto-excluding **/node_modules
2024-10-06 09:50:42.256 [info] [Info  - 9:50:42 AM] (3071) Auto-excluding **/__pycache__
2024-10-06 09:50:42.256 [info] [Info  - 9:50:42 AM] (3071) Auto-excluding **/.*
2024-10-06 09:50:43.338 [info] [Info  - 9:50:43 AM] (3071) Assuming Python version 3.8.16.final.0
2024-10-06 09:50:43.597 [info] [Info  - 9:50:43 AM] (3071) No source files found.
2024-10-06 09:50:43.710 [info] [Info  - 9:50:43 AM] (3071) Background analysis(1) root directory: file:///home/ec2-user/.vscode-server/extensions/ms-python.vscode-pylance-2024.9.2/dist
2024-10-06 09:50:43.715 [info] [Info  - 9:50:43 AM] (3071) Background analysis(1) started
2024-10-06 10:33:05.463 [info] [Info  - 10:33:05 AM] Server process exited successfully
2024-10-06 10:33:07.059 [info] (Client) Pylance async client (2024.9.2) started with python extension (2024.16.0)
2024-10-06 10:33:07.704 [info] [Info  - 10:33:07 AM] (3835) Server root directory: file:///home/ec2-user/.vscode-server/extensions/ms-python.vscode-pylance-2024.9.2/dist
2024-10-06 10:33:07.706 [info] [Info  - 10:33:07 AM] (3835) Pylance language server 2024.9.2 (pyright version 1.1.378, commit ce64adc1) starting
2024-10-06 10:33:07.715 [info] [Info  - 10:33:07 AM] (3835) Starting service instance "ec2-user"
2024-10-06 10:33:07.802 [info] [Info  - 10:33:07 AM] (3835) Setting environmentName for service "ec2-user": "3.8.16 (global)"
2024-10-06 10:33:07.803 [info] [Info  - 10:33:07 AM] (3835) Setting pythonPath for service "ec2-user": "/usr/bin/python3.8"
2024-10-06 10:33:07.803 [info] [Info  - 10:33:07 AM] (3835) No include entries specified; assuming /home/ec2-user
2024-10-06 10:33:07.805 [info] [Info  - 10:33:07 AM] (3835) Auto-excluding **/node_modules
2024-10-06 10:33:07.805 [info] [Info  - 10:33:07 AM] (3835) Auto-excluding **/__pycache__
2024-10-06 10:33:07.806 [info] [Info  - 10:33:07 AM] (3835) Auto-excluding **/.*
2024-10-06 10:33:07.862 [info] [Info  - 10:33:07 AM] (3835) Assuming Python version 3.8.16.final.0
2024-10-06 10:33:07.990 [info] [Info  - 10:33:07 AM] (3835) No source files found.
2024-10-06 10:33:08.662 [info] [Info  - 10:33:08 AM] (3835) Background analysis(1) root directory: file:///home/ec2-user/.vscode-server/extensions/ms-python.vscode-pylance-2024.9.2/dist
2024-10-06 10:33:08.671 [info] [Info  - 10:33:08 AM] (3835) Background analysis(1) started
2024-10-06 10:33:23.032 [info] [Info  - 10:33:23 AM] Server process exited successfully
2024-10-06 10:33:24.521 [info] (Client) Pylance async client (2024.9.2) started with python extension (2024.16.0)
2024-10-06 10:33:25.281 [info] [Info  - 10:33:25 AM] (3853) Server root directory: file:///home/ec2-user/.vscode-server/extensions/ms-python.vscode-pylance-2024.9.2/dist
2024-10-06 10:33:25.284 [info] [Info  - 10:33:25 AM] (3853) Pylance language server 2024.9.2 (pyright version 1.1.378, commit ce64adc1) starting
2024-10-06 10:33:25.292 [info] [Info  - 10:33:25 AM] (3853) Starting service instance "ec2-user"
2024-10-06 10:33:25.386 [info] [Info  - 10:33:25 AM] (3853) Setting environmentName for service "ec2-user": "3.8.16 (global)"
2024-10-06 10:33:25.387 [info] [Info  - 10:33:25 AM] (3853) Setting pythonPath for service "ec2-user": "/usr/bin/python3.8"
2024-10-06 10:33:25.387 [info] [Info  - 10:33:25 AM] (3853) No include entries specified; assuming /home/ec2-user
2024-10-06 10:33:25.387 [info] [Info  - 10:33:25 AM] (3853) Auto-excluding **/node_modules
2024-10-06 10:33:25.387 [info] [Info  - 10:33:25 AM] (3853) Auto-excluding **/__pycache__
2024-10-06 10:33:25.387 [info] [Info  - 10:33:25 AM] (3853) Auto-excluding **/.*
2024-10-06 10:33:25.441 [info] [Info  - 10:33:25 AM] (3853) Assuming Python version 3.8.16.final.0
2024-10-06 10:33:25.554 [info] [Info  - 10:33:25 AM] (3853) No source files found.
2024-10-06 10:33:26.220 [info] [Info  - 10:33:26 AM] (3853) Background analysis(1) root directory: file:///home/ec2-user/.vscode-server/extensions/ms-python.vscode-pylance-2024.9.2/dist
2024-10-06 10:33:26.225 [info] [Info  - 10:33:26 AM] (3853) Background analysis(1) started
